### ISSUE TITLE
Adapt new encryption method

### ISSUE THREAD

**Issue by jsampedro77** [jsampedro77/sermepa-omnipay#3]
Redsys has changed the encryption method and it must be adapted before November 23rd.

**Comment by jsampedro77** [comment]
@drmonkeyninja Are you aware of this? I am planning to solve this by this weekend.

**Comment by jsampedro77** [comment]
Done in 0.2 d32ce1d1c49098e28d08bd98acf6e4d73fa7b068

**Comment by drmonkeyninja** [comment]
@jsampedro77 I wasn't aware. Thanks for the update.

**Comment by jsampedro77** [comment]
A new method was added to Gateway to help recover returned parameters in callback

```
    public function decodeCallbackResponse(Request $request)
    {
        return json_decode(base64_decode(strtr($request->get('Ds_MerchantParameters'), '-_', '+/')), true);
    }
```
